// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429 : ICoherenceComponentData
	{
		public Vector3 position;
		public Quaternion rotation;
		public Vector3 scale;

		public override string ToString()
		{
			return $"AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429(position: {position}, rotation: {rotation}, scale: {scale})";
		}

		public uint GetComponentType() => Definition.InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;

		private static readonly float _position_Epsilon = 2.3283064365386963e-10f;
		private static readonly float _rotation_Epsilon = 2.3283064365386963e-10f;
		private static readonly float _scale_Epsilon = 2.3283064365386963e-10f;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				position = other.position;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				rotation = other.rotation;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				scale = other.scale;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			uint mask = 0;
			var newData = (AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429)data;

			if (position.DiffersFrom(newData.position, _position_Epsilon)) {
				mask |= 0b00000000000000000000000000000001;
			}
			if (rotation.DiffersFrom(newData.rotation, _rotation_Epsilon)) {
				mask |= 0b00000000000000000000000000000010;
			}
			if (scale.DiffersFrom(newData.scale, _scale_Epsilon)) {
				mask |= 0b00000000000000000000000000000100;
			}

			return mask;
		}

		public static void Serialize(AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.position.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteQuaternion((data.rotation.ToCoreQuaternion()), 32);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.scale.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429();
			if (bitStream.ReadMask())
			{
				val.position = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.rotation = (bitStream.ReadQuaternion(32)).ToUnityQuaternion();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.scale = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000100;
			}
			return (val, mask, null);
		}

		public static (AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429, uint, uint?) DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429();
			if (bitStream.ReadMask())
			{
				val.position = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.rotation = (bitStream.ReadQuaternion(32)).ToUnityQuaternion();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.scale = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000100;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429?;
		}
	}
}