// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int FloorPlane_8eb27a8d75b38914780fb01a3d8b2d6aIndex = 0;
		public const int AirHockeyTable_1b8979aab75cc3548ac0742146ec7eedIndex = 1;
		public const int Puck_67d153e8cb5779a49a2e569ee35a4437Index = 2;
		public const int Mallet_38e627b1eb339e74eb512bd8e1020e39Index = 3;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "FloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a", 0 },

			{ "AirHockeyTable_1b8979aab75cc3548ac0742146ec7eed", 1 },

			{ "Puck_67d153e8cb5779a49a2e569ee35a4437", 2 },

			{ "Mallet_38e627b1eb339e74eb512bd8e1020e39", 3 },

		};
	}
}
