// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Connection;
	using Coherence.Log;
	using UnityEngine.Scripting;

	using Logger = Coherence.Log.Logger;

	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'FloorPlane' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncFloorPlane_id0 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached references to MonoBehaviours on this GameObject
		private Coherence.Toolkit.CoherenceSync _transformViaCoherenceSync_8739119713596817957;
		private UnityEngine.MeshCollider _UnityEngine__char_46_MeshCollider_124998048203007390;

		// Last sent data for each component (used for diffing)
		private WorldPosition _transformViaCoherenceSync_8739119713596817957_WorldPosition_lastSentData = default;
		private WorldOrientation _transformViaCoherenceSync_8739119713596817957_WorldOrientation_lastSentData = default;
		private GenericScale _transformViaCoherenceSync_8739119713596817957_GenericScale_lastSentData = default;
		private FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390 _UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData = default;

		// Cached targets for commands	

		private string lastSerializedCoherenceUUID;
		private bool performedInitialSync = false;
		private IBinding InternalWorldPosition_Translation_value_Binding;
		private IBinding InternalWorldOrientation_Rotation_value_Binding;
		private IBinding InternalGenericScale_GenericScale_value_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding;
		private IBinding InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;
		private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
		private CoherenceInput coherenceInput;

		private List<ComponentChange> updateBuff = new List<ComponentChange>(16);
		private Dictionary<SerializeEntityID, EntityData> delayedEntityReferences;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;
			coherenceInput = coherenceSync.Input;

			logger = coherenceSync.logger.With<CoherenceSyncFloorPlane_id0>();

			if (coherenceSync.TryGetBindingByGuid("35dee6bd-2a81-4667-b26c-acc0b7a9d3d2", "position", out InternalWorldPosition_Translation_value_Binding))
			{
				_transformViaCoherenceSync_8739119713596817957 = (Coherence.Toolkit.CoherenceSync)InternalWorldPosition_Translation_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}

			if (coherenceSync.TryGetBindingByGuid("208d82b8-645f-47ea-abfd-070c51559ba8", "rotation", out InternalWorldOrientation_Rotation_value_Binding))
			{
				_transformViaCoherenceSync_8739119713596817957 = (Coherence.Toolkit.CoherenceSync)InternalWorldOrientation_Rotation_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}

			if (coherenceSync.TryGetBindingByGuid("e46a59ee-ea9b-416f-96be-ce543e02a8fe", "scale", out InternalGenericScale_GenericScale_value_Binding))
			{
				_transformViaCoherenceSync_8739119713596817957 = (Coherence.Toolkit.CoherenceSync)InternalGenericScale_GenericScale_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).scale");
			}

			if (coherenceSync.TryGetBindingByGuid("9e1b1d38-a038-4365-a61d-7d9414396346", "convex", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).convex");
			}

			if (coherenceSync.TryGetBindingByGuid("b1ed2206-4b80-4b99-b954-312f96ed9583", "skinWidth", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).skinWidth");
			}

			if (coherenceSync.TryGetBindingByGuid("b9439128-a187-4938-b31d-ec633d407ba7", "inflateMesh", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).inflateMesh");
			}

			if (coherenceSync.TryGetBindingByGuid("5aa14e34-b4e4-429c-b8db-9592e1e80c44", "enabled", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).enabled");
			}

			if (coherenceSync.TryGetBindingByGuid("eb7bb090-accf-4914-bb10-85ee333e8e29", "isTrigger", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).isTrigger");
			}

			if (coherenceSync.TryGetBindingByGuid("a6f1a076-7aa6-4b09-860e-479f16be96d4", "contactOffset", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).contactOffset");
			}

			if (coherenceSync.TryGetBindingByGuid("9e646241-9e18-4fd2-b8b8-05b0f12f8f98", "hasModifiableContacts", out InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding))
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390 = (UnityEngine.MeshCollider)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshCollider).hasModifiableContacts");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime)
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = Archetypes.IndexForName[coherenceSync.Archetype.ArchetypeName]
					}
				};

				return components;
			}

			return null;
		}

		private void OnDestroy()
		{
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}

			this.client = client;

			lastSerializedCoherenceUUID = coherenceSync.coherenceUUID;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncFloorPlane_id0] Unhandled command: {command.GetType()}.");
					break;
			}
		}

		public override void SendUpdates()
		{
			SendComponentUpdates();
		}

		public override (List<ICoherenceComponentData>, List<uint>) GetLatestChanges()
		{
			var updates = new List<ICoherenceComponentData>();
			var masks = new List<uint>();

			if (coherenceSync.HasStateAuthority)
			{

				// Send Translation / WorldPosition
				{
					var update = _transformViaCoherenceSync_8739119713596817957_WorldPosition_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalWorldPosition_Translation_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_8739119713596817957.coherencePosition);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_8739119713596817957_WorldPosition_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_8739119713596817957_WorldPosition_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_8739119713596817957_WorldPosition_lastSentData = update;
					}
				}

				// Send Rotation / WorldOrientation
				{
					var update = _transformViaCoherenceSync_8739119713596817957_WorldOrientation_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalWorldOrientation_Rotation_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_8739119713596817957.coherenceRotation);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_8739119713596817957_WorldOrientation_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_8739119713596817957_WorldOrientation_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_8739119713596817957_WorldOrientation_lastSentData = update;
					}
				}

				// Send GenericScale / GenericScale
				{
					var update = _transformViaCoherenceSync_8739119713596817957_GenericScale_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalGenericScale_GenericScale_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_8739119713596817957.coherenceLocalScale);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_8739119713596817957_GenericScale_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_8739119713596817957_GenericScale_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_8739119713596817957_GenericScale_lastSentData = update;
					}
				}

				// Send FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390 / FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390
				{
					var update = _UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.convex = (_UnityEngine__char_46_MeshCollider_124998048203007390.convex);
					}
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.skinWidth = (_UnityEngine__char_46_MeshCollider_124998048203007390.skinWidth);
					}
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.inflateMesh = (_UnityEngine__char_46_MeshCollider_124998048203007390.inflateMesh);
					}
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.enabled = (_UnityEngine__char_46_MeshCollider_124998048203007390.enabled);
					}
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.isTrigger = (_UnityEngine__char_46_MeshCollider_124998048203007390.isTrigger);
					}
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.contactOffset = (_UnityEngine__char_46_MeshCollider_124998048203007390.contactOffset);
					}
					if (coherenceSync.IsReadyToSample(InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.hasModifiableContacts = (_UnityEngine__char_46_MeshCollider_124998048203007390.hasModifiableContacts);
					}

					uint mask = performedInitialSync ? _UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData = update;
					}
				}

				if (coherenceSync.coherenceUUID != lastSerializedCoherenceUUID)
				{
					var update = Impl.GetRootDefinition().GenerateCoherenceUUIDData(coherenceSync.coherenceUUID);
					var mask = 0b11111111111111111111111111111111;

					updates.Add(update);
					masks.Add(mask);

					lastSerializedCoherenceUUID = coherenceSync.coherenceUUID;
				}
				performedInitialSync = true;
			}

			return (updates, masks);
		}

		public override void PerformInterpolation()
		{
			if (InternalWorldPosition_Translation_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_8739119713596817957.coherencePosition = (UnityEngine.Vector3)InternalWorldPosition_Translation_value_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_transformViaCoherenceSync_8739119713596817957.coherencePosition, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalWorldOrientation_Rotation_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_8739119713596817957.coherenceRotation = (UnityEngine.Quaternion)InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_transformViaCoherenceSync_8739119713596817957.coherenceRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalGenericScale_GenericScale_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_8739119713596817957.coherenceLocalScale = (UnityEngine.Vector3)InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_transformViaCoherenceSync_8739119713596817957.coherenceLocalScale, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.convex = (System.Boolean)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_MeshCollider_124998048203007390.convex, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.skinWidth = (System.Single)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_MeshCollider_124998048203007390.skinWidth, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.inflateMesh = (System.Boolean)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_MeshCollider_124998048203007390.inflateMesh, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.enabled = (System.Boolean)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_MeshCollider_124998048203007390.enabled, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.isTrigger = (System.Boolean)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_MeshCollider_124998048203007390.isTrigger, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.contactOffset = (System.Single)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_MeshCollider_124998048203007390.contactOffset, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390.hasModifiableContacts = (System.Boolean)InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_MeshCollider_124998048203007390.hasModifiableContacts, monoBridge.NetworkTime.TimeAsDouble) ;
			}
		}

		public override void ResetInterpolation(bool setToLastSamples)
		{
			if (setToLastSamples && InternalWorldPosition_Translation_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalWorldPosition_Translation_value_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_transformViaCoherenceSync_8739119713596817957.coherencePosition = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalWorldPosition_Translation_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_transformViaCoherenceSync_8739119713596817957.coherenceRotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_transformViaCoherenceSync_8739119713596817957.coherenceLocalScale = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.convex = (System.Boolean)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.skinWidth = (System.Single)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.inflateMesh = (System.Boolean)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.enabled = (System.Boolean)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.isTrigger = (System.Boolean)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.contactOffset = (System.Single)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_MeshCollider_124998048203007390.hasModifiableContacts = (System.Boolean)lastSample;
				}
			}
			InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.InterpolationSettings.Reset();
		}		

		public override void ResetLastSentData()
		{
			// Translation / WorldPosition
			{
				_transformViaCoherenceSync_8739119713596817957_WorldPosition_lastSentData.value = (_transformViaCoherenceSync_8739119713596817957.coherencePosition);
			}
			// Rotation / WorldOrientation
			{
				_transformViaCoherenceSync_8739119713596817957_WorldOrientation_lastSentData.value = (_transformViaCoherenceSync_8739119713596817957.coherenceRotation);
			}
			// GenericScale / GenericScale
			{
				_transformViaCoherenceSync_8739119713596817957_GenericScale_lastSentData.value = (_transformViaCoherenceSync_8739119713596817957.coherenceLocalScale);
			}
			// FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390 / FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390
			{
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.convex = (_UnityEngine__char_46_MeshCollider_124998048203007390.convex);
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.skinWidth = (_UnityEngine__char_46_MeshCollider_124998048203007390.skinWidth);
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.inflateMesh = (_UnityEngine__char_46_MeshCollider_124998048203007390.inflateMesh);
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.enabled = (_UnityEngine__char_46_MeshCollider_124998048203007390.enabled);
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.isTrigger = (_UnityEngine__char_46_MeshCollider_124998048203007390.isTrigger);
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.contactOffset = (_UnityEngine__char_46_MeshCollider_124998048203007390.contactOffset);
				_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_lastSentData.hasModifiableContacts = (_UnityEngine__char_46_MeshCollider_124998048203007390.hasModifiableContacts);
			}
		}

		private void SendComponentUpdates()
		{
			var entity = coherenceSync.EntityID;

			if (coherenceSync.HasStateAuthority)
			{
				var (updates, masks) = GetLatestChanges();

				if (updates.Count > 0)
				{
					client.UpdateComponents(coherenceSync.EntityID, updates.ToArray(), masks.ToArray());
				}
			}
		}

		public override void ApplyComponentUpdates(EntityData entityData)
		{
			// Sort component changes by (order, index) using Linq to ensure consistent replication order, regardless of ordering in packet.
			// Multiplying by a constant value is faster than using Linq .ThenBy extension method.
			updateBuff.Clear();
			updateBuff.AddRange(entityData.Store.Values);
			updateBuff.Sort((a, b) => (a.Data.GetComponentOrder() * 10000 + a.Data.GetComponentType()).CompareTo(
				b.Data.GetComponentOrder() * 10000 + b.Data.GetComponentType()));

			foreach (var change in updateBuff)
			{
				var componentType = change.Data.GetComponentType();

				switch(componentType)
				{

					case 0:
					{
						// Translation
						var data = (WorldPosition)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalWorldPosition_Translation_value_Binding.ReceiveSampleFromNetwork<Vector3>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 1:
					{
						// Rotation
						var data = (WorldOrientation)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalWorldOrientation_Rotation_value_Binding.ReceiveSampleFromNetwork<Quaternion>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 15:
					{
						// GenericScale
						var data = (GenericScale)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalGenericScale_GenericScale_value_Binding.ReceiveSampleFromNetwork<Vector3>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 91:
					{
						// FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390
						var data = (FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_convex_Binding.ReceiveSampleFromNetwork<bool>(data.convex, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000000010) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_skinWidth_Binding.ReceiveSampleFromNetwork<float>(data.skinWidth, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000000100) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_inflateMesh_Binding.ReceiveSampleFromNetwork<bool>(data.inflateMesh, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000001000) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_enabled_Binding.ReceiveSampleFromNetwork<bool>(data.enabled, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000010000) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_isTrigger_Binding.ReceiveSampleFromNetwork<bool>(data.isTrigger, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000100000) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_contactOffset_Binding.ReceiveSampleFromNetwork<float>(data.contactOffset, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000001000000) != 0)
						{
							InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_hasModifiableContacts_Binding.ReceiveSampleFromNetwork<bool>(data.hasModifiableContacts, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case Definition.InternalArchetypeComponent:
						// Handled internally by coherence Client Core
						break;
					case Definition.InternalGenericPrefabReference:
						// Handled internally by the coherence Mono Bridge
						break;
					case Definition.InternalUniqueID:
						coherenceSync.coherenceUUID = lastSerializedCoherenceUUID = Impl.GetRootDefinition().ExtractCoherenceUUID(change.Data);
						break;
					case Definition.InternalPersistence:
						break;
					case Definition.InternalConnectedEntity:
						var newConnectedEntity = Impl.GetRootDefinition().ExtractConnectedEntityID(change.Data);
						coherenceSync.ConnectedEntityChanged(newConnectedEntity);
						break;
					case Definition.InternalConnection:
					case Definition.InternalGlobal:
					case Definition.InternalGlobalQuery:
					case Definition.InternalTag:
					case Definition.InternalTagQuery:
					case Definition.InternalWorldPositionQuery:
						break;
					default:
						logger.Warning($"Unhandled component type ID: {componentType}");
						break;
					}
			}
		}

		private void AddDelayedEntityReference(SerializeEntityID id, ComponentChange componentChange)
		{
			if (delayedEntityReferences == null)
			{
				delayedEntityReferences = new Dictionary<SerializeEntityID, EntityData>();
			}

			EntityData entityData;

			if (!delayedEntityReferences.TryGetValue(id, out entityData))
			{
				entityData = EntityData.New();
			}

			entityData.Update(componentChange);
			delayedEntityReferences[id] = entityData;
		}

		private T FindCommandTarget<T>() where T : class
		{
			var targets = GetComponentsInChildren<T>();

			if (targets == null || targets.Length == 0)
			{
				logger.Error($"Couldn't find {nameof(T)} component in children.");
				
				return null;
			}

			if (targets.Length > 1)
			{
				logger.Error($"Found more than one {nameof(T)} component in children.");
			}

			return targets[0];
		}
	}
}
