// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Connection;
	using Coherence.Log;
	using UnityEngine.Scripting;

	using Logger = Coherence.Log.Logger;

	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Mallet' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncMallet_id3 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached references to MonoBehaviours on this GameObject
		private Coherence.Toolkit.CoherenceSync _transformViaCoherenceSync_5326138786584244737;
		private UnityEngine.Rigidbody _UnityEngine__char_46_Rigidbody_3239353100064038034;

		// Last sent data for each component (used for diffing)
		private WorldPosition _transformViaCoherenceSync_5326138786584244737_WorldPosition_lastSentData = default;
		private WorldOrientation _transformViaCoherenceSync_5326138786584244737_WorldOrientation_lastSentData = default;
		private GenericScale _transformViaCoherenceSync_5326138786584244737_GenericScale_lastSentData = default;
		private Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034 _UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData = default;

		// Cached targets for commands	

		private string lastSerializedCoherenceUUID;
		private bool performedInitialSync = false;
		private IBinding InternalWorldPosition_Translation_value_Binding;
		private IBinding InternalWorldOrientation_Rotation_value_Binding;
		private IBinding InternalGenericScale_GenericScale_value_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding;
		private IBinding InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;
		private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
		private CoherenceInput coherenceInput;

		private List<ComponentChange> updateBuff = new List<ComponentChange>(16);
		private Dictionary<SerializeEntityID, EntityData> delayedEntityReferences;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;
			coherenceInput = coherenceSync.Input;

			logger = coherenceSync.logger.With<CoherenceSyncMallet_id3>();

			if (coherenceSync.TryGetBindingByGuid("b4382f82-d5e3-46fb-95f2-3a1b76c85174", "position", out InternalWorldPosition_Translation_value_Binding))
			{
				_transformViaCoherenceSync_5326138786584244737 = (Coherence.Toolkit.CoherenceSync)InternalWorldPosition_Translation_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}

			if (coherenceSync.TryGetBindingByGuid("3dcecdf8-5784-40ef-9da5-0848f6bd556a", "rotation", out InternalWorldOrientation_Rotation_value_Binding))
			{
				_transformViaCoherenceSync_5326138786584244737 = (Coherence.Toolkit.CoherenceSync)InternalWorldOrientation_Rotation_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}

			if (coherenceSync.TryGetBindingByGuid("3ffade1c-041a-45b7-af8b-5d37bbbb2b0f", "scale", out InternalGenericScale_GenericScale_value_Binding))
			{
				_transformViaCoherenceSync_5326138786584244737 = (Coherence.Toolkit.CoherenceSync)InternalGenericScale_GenericScale_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).scale");
			}

			if (coherenceSync.TryGetBindingByGuid("a541efd0-369b-4e3e-91ff-8df163a60fba", "velocity", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).velocity");
			}

			if (coherenceSync.TryGetBindingByGuid("72e18921-a8a3-4672-a37e-01e0b30fcfb2", "angularVelocity", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).angularVelocity");
			}

			if (coherenceSync.TryGetBindingByGuid("1be7eb57-b6c4-48b9-8c93-9f6669d52862", "drag", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).drag");
			}

			if (coherenceSync.TryGetBindingByGuid("10b39dc9-af1d-4afc-b9ab-e0b83571a00a", "angularDrag", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).angularDrag");
			}

			if (coherenceSync.TryGetBindingByGuid("43f75417-8172-42b7-953e-2c74ae5ff747", "mass", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).mass");
			}

			if (coherenceSync.TryGetBindingByGuid("d3428390-350c-4bfb-a24e-3e6386c67c4a", "useGravity", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).useGravity");
			}

			if (coherenceSync.TryGetBindingByGuid("69f71b6f-7e7a-47a2-ad1a-eb380b679a6f", "maxDepenetrationVelocity", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).maxDepenetrationVelocity");
			}

			if (coherenceSync.TryGetBindingByGuid("af1289cb-960d-4ede-bb7a-70aa6a1650d8", "isKinematic", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).isKinematic");
			}

			if (coherenceSync.TryGetBindingByGuid("0d594cae-52d0-4808-9c9f-8e6eaf36f997", "freezeRotation", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).freezeRotation");
			}

			if (coherenceSync.TryGetBindingByGuid("f1f71f95-6305-45b5-96eb-86d2e097ff76", "centerOfMass", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).centerOfMass");
			}

			if (coherenceSync.TryGetBindingByGuid("e06e88c1-44fe-4d95-9590-8a15194eef25", "inertiaTensorRotation", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).inertiaTensorRotation");
			}

			if (coherenceSync.TryGetBindingByGuid("02261d26-f183-466f-bab4-73a9f7344162", "inertiaTensor", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).inertiaTensor");
			}

			if (coherenceSync.TryGetBindingByGuid("cf660926-e76a-429e-948c-a5df0efe7d2e", "detectCollisions", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).detectCollisions");
			}

			if (coherenceSync.TryGetBindingByGuid("a9c90ab5-74ad-492f-97a9-72883d5f361e", "position", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).position");
			}

			if (coherenceSync.TryGetBindingByGuid("afefe0cd-ddb7-4bd8-a379-df52257d2e2d", "rotation", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).rotation");
			}

			if (coherenceSync.TryGetBindingByGuid("3ccb70f9-9335-4084-b3b5-93300cf5a7ea", "solverIterations", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverIterations");
			}

			if (coherenceSync.TryGetBindingByGuid("3887e586-6dff-4fa1-81b1-4abcfdbebc20", "sleepThreshold", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).sleepThreshold");
			}

			if (coherenceSync.TryGetBindingByGuid("cf06a291-50ea-4ef3-98c2-e34cb584c01a", "maxAngularVelocity", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).maxAngularVelocity");
			}

			if (coherenceSync.TryGetBindingByGuid("3549093e-82ba-4bcd-ab2e-ce355f2e2112", "solverVelocityIterations", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverVelocityIterations");
			}

			if (coherenceSync.TryGetBindingByGuid("640a3a73-7a8a-4b93-ac23-0cd3b610dbd9", "solverIterationCount", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverIterationCount");
			}

			if (coherenceSync.TryGetBindingByGuid("60784cd0-325d-4f88-9874-0fe426ad5f81", "solverVelocityIterationCount", out InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding))
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034 = (UnityEngine.Rigidbody)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverVelocityIterationCount");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime)
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = Archetypes.IndexForName[coherenceSync.Archetype.ArchetypeName]
					}
				};

				return components;
			}

			return null;
		}

		private void OnDestroy()
		{
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}

			this.client = client;

			lastSerializedCoherenceUUID = coherenceSync.coherenceUUID;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncMallet_id3] Unhandled command: {command.GetType()}.");
					break;
			}
		}

		public override void SendUpdates()
		{
			SendComponentUpdates();
		}

		public override (List<ICoherenceComponentData>, List<uint>) GetLatestChanges()
		{
			var updates = new List<ICoherenceComponentData>();
			var masks = new List<uint>();

			if (coherenceSync.HasStateAuthority)
			{

				// Send Translation / WorldPosition
				{
					var update = _transformViaCoherenceSync_5326138786584244737_WorldPosition_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalWorldPosition_Translation_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_5326138786584244737.coherencePosition);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_5326138786584244737_WorldPosition_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_5326138786584244737_WorldPosition_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_5326138786584244737_WorldPosition_lastSentData = update;
					}
				}

				// Send Rotation / WorldOrientation
				{
					var update = _transformViaCoherenceSync_5326138786584244737_WorldOrientation_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalWorldOrientation_Rotation_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_5326138786584244737.coherenceRotation);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_5326138786584244737_WorldOrientation_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_5326138786584244737_WorldOrientation_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_5326138786584244737_WorldOrientation_lastSentData = update;
					}
				}

				// Send GenericScale / GenericScale
				{
					var update = _transformViaCoherenceSync_5326138786584244737_GenericScale_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalGenericScale_GenericScale_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_5326138786584244737.coherenceLocalScale);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_5326138786584244737_GenericScale_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_5326138786584244737_GenericScale_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_5326138786584244737_GenericScale_lastSentData = update;
					}
				}

				// Send Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034 / Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034
				{
					var update = _UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.velocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.velocity);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.angularVelocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.angularVelocity);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.drag = (_UnityEngine__char_46_Rigidbody_3239353100064038034.drag);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.angularDrag = (_UnityEngine__char_46_Rigidbody_3239353100064038034.angularDrag);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.mass = (_UnityEngine__char_46_Rigidbody_3239353100064038034.mass);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.useGravity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.useGravity);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.maxDepenetrationVelocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.maxDepenetrationVelocity);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.isKinematic = (_UnityEngine__char_46_Rigidbody_3239353100064038034.isKinematic);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.freezeRotation = (_UnityEngine__char_46_Rigidbody_3239353100064038034.freezeRotation);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.centerOfMass = (_UnityEngine__char_46_Rigidbody_3239353100064038034.centerOfMass);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.inertiaTensorRotation = (_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensorRotation);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.inertiaTensor = (_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensor);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.detectCollisions = (_UnityEngine__char_46_Rigidbody_3239353100064038034.detectCollisions);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.position = (_UnityEngine__char_46_Rigidbody_3239353100064038034.position);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.rotation = (_UnityEngine__char_46_Rigidbody_3239353100064038034.rotation);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverIterations = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.sleepThreshold = (_UnityEngine__char_46_Rigidbody_3239353100064038034.sleepThreshold);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.maxAngularVelocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.maxAngularVelocity);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverVelocityIterations = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverIterationCount = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations);
					}
					if (coherenceSync.IsReadyToSample(InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverVelocityIterationCount = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations);
					}

					uint mask = performedInitialSync ? _UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData = update;
					}
				}

				if (coherenceSync.coherenceUUID != lastSerializedCoherenceUUID)
				{
					var update = Impl.GetRootDefinition().GenerateCoherenceUUIDData(coherenceSync.coherenceUUID);
					var mask = 0b11111111111111111111111111111111;

					updates.Add(update);
					masks.Add(mask);

					lastSerializedCoherenceUUID = coherenceSync.coherenceUUID;
				}
				performedInitialSync = true;
			}

			return (updates, masks);
		}

		public override void PerformInterpolation()
		{
			if (InternalWorldPosition_Translation_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_5326138786584244737.coherencePosition = (UnityEngine.Vector3)InternalWorldPosition_Translation_value_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_transformViaCoherenceSync_5326138786584244737.coherencePosition, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalWorldOrientation_Rotation_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_5326138786584244737.coherenceRotation = (UnityEngine.Quaternion)InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_transformViaCoherenceSync_5326138786584244737.coherenceRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalGenericScale_GenericScale_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_5326138786584244737.coherenceLocalScale = (UnityEngine.Vector3)InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_transformViaCoherenceSync_5326138786584244737.coherenceLocalScale, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.velocity = (UnityEngine.Vector3)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_3239353100064038034.velocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.angularVelocity = (UnityEngine.Vector3)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_3239353100064038034.angularVelocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.drag = (System.Single)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_3239353100064038034.drag, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.angularDrag = (System.Single)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_3239353100064038034.angularDrag, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.mass = (System.Single)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_3239353100064038034.mass, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.useGravity = (System.Boolean)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_3239353100064038034.useGravity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.maxDepenetrationVelocity = (System.Single)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_3239353100064038034.maxDepenetrationVelocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.isKinematic = (System.Boolean)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_3239353100064038034.isKinematic, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.freezeRotation = (System.Boolean)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_3239353100064038034.freezeRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.centerOfMass = (UnityEngine.Vector3)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_3239353100064038034.centerOfMass, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensorRotation = (UnityEngine.Quaternion)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensorRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensor = (UnityEngine.Vector3)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensor, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.detectCollisions = (System.Boolean)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_3239353100064038034.detectCollisions, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.position = (UnityEngine.Vector3)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_3239353100064038034.position, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.rotation = (UnityEngine.Quaternion)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_UnityEngine__char_46_Rigidbody_3239353100064038034.rotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations = (System.Int32)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.sleepThreshold = (System.Single)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_3239353100064038034.sleepThreshold, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.maxAngularVelocity = (System.Single)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_3239353100064038034.maxAngularVelocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations = (System.Int32)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations = (System.Int32)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations = (System.Int32)InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
		}

		public override void ResetInterpolation(bool setToLastSamples)
		{
			if (setToLastSamples && InternalWorldPosition_Translation_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalWorldPosition_Translation_value_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_transformViaCoherenceSync_5326138786584244737.coherencePosition = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalWorldPosition_Translation_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_transformViaCoherenceSync_5326138786584244737.coherenceRotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_transformViaCoherenceSync_5326138786584244737.coherenceLocalScale = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.velocity = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.angularVelocity = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.drag = (System.Single)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.angularDrag = (System.Single)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.mass = (System.Single)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.useGravity = (System.Boolean)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.maxDepenetrationVelocity = (System.Single)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.isKinematic = (System.Boolean)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.freezeRotation = (System.Boolean)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.centerOfMass = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensorRotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensor = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.detectCollisions = (System.Boolean)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.position = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.rotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations = (System.Int32)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.sleepThreshold = (System.Single)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.maxAngularVelocity = (System.Single)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations = (System.Int32)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations = (System.Int32)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations = (System.Int32)lastSample;
				}
			}
			InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.InterpolationSettings.Reset();
		}		

		public override void ResetLastSentData()
		{
			// Translation / WorldPosition
			{
				_transformViaCoherenceSync_5326138786584244737_WorldPosition_lastSentData.value = (_transformViaCoherenceSync_5326138786584244737.coherencePosition);
			}
			// Rotation / WorldOrientation
			{
				_transformViaCoherenceSync_5326138786584244737_WorldOrientation_lastSentData.value = (_transformViaCoherenceSync_5326138786584244737.coherenceRotation);
			}
			// GenericScale / GenericScale
			{
				_transformViaCoherenceSync_5326138786584244737_GenericScale_lastSentData.value = (_transformViaCoherenceSync_5326138786584244737.coherenceLocalScale);
			}
			// Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034 / Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034
			{
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.velocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.velocity);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.angularVelocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.angularVelocity);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.drag = (_UnityEngine__char_46_Rigidbody_3239353100064038034.drag);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.angularDrag = (_UnityEngine__char_46_Rigidbody_3239353100064038034.angularDrag);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.mass = (_UnityEngine__char_46_Rigidbody_3239353100064038034.mass);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.useGravity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.useGravity);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.maxDepenetrationVelocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.maxDepenetrationVelocity);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.isKinematic = (_UnityEngine__char_46_Rigidbody_3239353100064038034.isKinematic);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.freezeRotation = (_UnityEngine__char_46_Rigidbody_3239353100064038034.freezeRotation);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.centerOfMass = (_UnityEngine__char_46_Rigidbody_3239353100064038034.centerOfMass);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.inertiaTensorRotation = (_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensorRotation);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.inertiaTensor = (_UnityEngine__char_46_Rigidbody_3239353100064038034.inertiaTensor);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.detectCollisions = (_UnityEngine__char_46_Rigidbody_3239353100064038034.detectCollisions);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.position = (_UnityEngine__char_46_Rigidbody_3239353100064038034.position);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.rotation = (_UnityEngine__char_46_Rigidbody_3239353100064038034.rotation);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.solverIterations = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.sleepThreshold = (_UnityEngine__char_46_Rigidbody_3239353100064038034.sleepThreshold);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.maxAngularVelocity = (_UnityEngine__char_46_Rigidbody_3239353100064038034.maxAngularVelocity);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.solverVelocityIterations = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.solverIterationCount = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverIterations);
				_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_lastSentData.solverVelocityIterationCount = (_UnityEngine__char_46_Rigidbody_3239353100064038034.solverVelocityIterations);
			}
		}

		private void SendComponentUpdates()
		{
			var entity = coherenceSync.EntityID;

			if (coherenceSync.HasStateAuthority)
			{
				var (updates, masks) = GetLatestChanges();

				if (updates.Count > 0)
				{
					client.UpdateComponents(coherenceSync.EntityID, updates.ToArray(), masks.ToArray());
				}
			}
		}

		public override void ApplyComponentUpdates(EntityData entityData)
		{
			// Sort component changes by (order, index) using Linq to ensure consistent replication order, regardless of ordering in packet.
			// Multiplying by a constant value is faster than using Linq .ThenBy extension method.
			updateBuff.Clear();
			updateBuff.AddRange(entityData.Store.Values);
			updateBuff.Sort((a, b) => (a.Data.GetComponentOrder() * 10000 + a.Data.GetComponentType()).CompareTo(
				b.Data.GetComponentOrder() * 10000 + b.Data.GetComponentType()));

			foreach (var change in updateBuff)
			{
				var componentType = change.Data.GetComponentType();

				switch(componentType)
				{

					case 0:
					{
						// Translation
						var data = (WorldPosition)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalWorldPosition_Translation_value_Binding.ReceiveSampleFromNetwork<Vector3>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 1:
					{
						// Rotation
						var data = (WorldOrientation)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalWorldOrientation_Rotation_value_Binding.ReceiveSampleFromNetwork<Quaternion>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 15:
					{
						// GenericScale
						var data = (GenericScale)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalGenericScale_GenericScale_value_Binding.ReceiveSampleFromNetwork<Vector3>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 112:
					{
						// Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034
						var data = (Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_velocity_Binding.ReceiveSampleFromNetwork<Vector3>(data.velocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000000010) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularVelocity_Binding.ReceiveSampleFromNetwork<Vector3>(data.angularVelocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000000100) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_drag_Binding.ReceiveSampleFromNetwork<float>(data.drag, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000001000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_angularDrag_Binding.ReceiveSampleFromNetwork<float>(data.angularDrag, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000010000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_mass_Binding.ReceiveSampleFromNetwork<float>(data.mass, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000100000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_useGravity_Binding.ReceiveSampleFromNetwork<bool>(data.useGravity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000001000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxDepenetrationVelocity_Binding.ReceiveSampleFromNetwork<float>(data.maxDepenetrationVelocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000010000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_isKinematic_Binding.ReceiveSampleFromNetwork<bool>(data.isKinematic, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000100000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_freezeRotation_Binding.ReceiveSampleFromNetwork<bool>(data.freezeRotation, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000001000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_centerOfMass_Binding.ReceiveSampleFromNetwork<Vector3>(data.centerOfMass, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000010000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensorRotation_Binding.ReceiveSampleFromNetwork<Quaternion>(data.inertiaTensorRotation, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000100000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_inertiaTensor_Binding.ReceiveSampleFromNetwork<Vector3>(data.inertiaTensor, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000001000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_detectCollisions_Binding.ReceiveSampleFromNetwork<bool>(data.detectCollisions, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000010000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_position_Binding.ReceiveSampleFromNetwork<Vector3>(data.position, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000100000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_rotation_Binding.ReceiveSampleFromNetwork<Quaternion>(data.rotation, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000001000000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterations_Binding.ReceiveSampleFromNetwork<int>(data.solverIterations, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000010000000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_sleepThreshold_Binding.ReceiveSampleFromNetwork<float>(data.sleepThreshold, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000100000000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_maxAngularVelocity_Binding.ReceiveSampleFromNetwork<float>(data.maxAngularVelocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000001000000000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterations_Binding.ReceiveSampleFromNetwork<int>(data.solverVelocityIterations, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000010000000000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverIterationCount_Binding.ReceiveSampleFromNetwork<int>(data.solverIterationCount, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000100000000000000000000) != 0)
						{
							InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_solverVelocityIterationCount_Binding.ReceiveSampleFromNetwork<int>(data.solverVelocityIterationCount, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case Definition.InternalArchetypeComponent:
						// Handled internally by coherence Client Core
						break;
					case Definition.InternalGenericPrefabReference:
						// Handled internally by the coherence Mono Bridge
						break;
					case Definition.InternalUniqueID:
						coherenceSync.coherenceUUID = lastSerializedCoherenceUUID = Impl.GetRootDefinition().ExtractCoherenceUUID(change.Data);
						break;
					case Definition.InternalPersistence:
						break;
					case Definition.InternalConnectedEntity:
						var newConnectedEntity = Impl.GetRootDefinition().ExtractConnectedEntityID(change.Data);
						coherenceSync.ConnectedEntityChanged(newConnectedEntity);
						break;
					case Definition.InternalConnection:
					case Definition.InternalGlobal:
					case Definition.InternalGlobalQuery:
					case Definition.InternalTag:
					case Definition.InternalTagQuery:
					case Definition.InternalWorldPositionQuery:
						break;
					default:
						logger.Warning($"Unhandled component type ID: {componentType}");
						break;
					}
			}
		}

		private void AddDelayedEntityReference(SerializeEntityID id, ComponentChange componentChange)
		{
			if (delayedEntityReferences == null)
			{
				delayedEntityReferences = new Dictionary<SerializeEntityID, EntityData>();
			}

			EntityData entityData;

			if (!delayedEntityReferences.TryGetValue(id, out entityData))
			{
				entityData = EntityData.New();
			}

			entityData.Update(componentChange);
			delayedEntityReferences[id] = entityData;
		}

		private T FindCommandTarget<T>() where T : class
		{
			var targets = GetComponentsInChildren<T>();

			if (targets == null || targets.Length == 0)
			{
				logger.Error($"Couldn't find {nameof(T)} component in children.");
				
				return null;
			}

			if (targets.Length > 1)
			{
				logger.Error($"Found more than one {nameof(T)} component in children.");
			}

			return targets[0];
		}
	}
}
