// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Connection;
	using Coherence.Log;
	using UnityEngine.Scripting;

	using Logger = Coherence.Log.Logger;

	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Puck' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncPuck_id2 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached references to MonoBehaviours on this GameObject
		private Coherence.Toolkit.CoherenceSync _transformViaCoherenceSync_2515451422962040544;
		private UnityEngine.Rigidbody _UnityEngine__char_46_Rigidbody_2515451422962040547;

		// Last sent data for each component (used for diffing)
		private WorldPosition _transformViaCoherenceSync_2515451422962040544_WorldPosition_lastSentData = default;
		private WorldOrientation _transformViaCoherenceSync_2515451422962040544_WorldOrientation_lastSentData = default;
		private GenericScale _transformViaCoherenceSync_2515451422962040544_GenericScale_lastSentData = default;
		private Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547 _UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData = default;

		// Cached targets for commands	

		private string lastSerializedCoherenceUUID;
		private bool performedInitialSync = false;
		private IBinding InternalWorldPosition_Translation_value_Binding;
		private IBinding InternalWorldOrientation_Rotation_value_Binding;
		private IBinding InternalGenericScale_GenericScale_value_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding;
		private IBinding InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;
		private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;
		private CoherenceInput coherenceInput;

		private List<ComponentChange> updateBuff = new List<ComponentChange>(16);
		private Dictionary<SerializeEntityID, EntityData> delayedEntityReferences;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;
			coherenceInput = coherenceSync.Input;

			logger = coherenceSync.logger.With<CoherenceSyncPuck_id2>();

			if (coherenceSync.TryGetBindingByGuid("de0edf25-1074-4790-b9c5-8df3fc238b29", "position", out InternalWorldPosition_Translation_value_Binding))
			{
				_transformViaCoherenceSync_2515451422962040544 = (Coherence.Toolkit.CoherenceSync)InternalWorldPosition_Translation_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}

			if (coherenceSync.TryGetBindingByGuid("abcbaad6-aa15-4424-af25-f21a042a711e", "rotation", out InternalWorldOrientation_Rotation_value_Binding))
			{
				_transformViaCoherenceSync_2515451422962040544 = (Coherence.Toolkit.CoherenceSync)InternalWorldOrientation_Rotation_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}

			if (coherenceSync.TryGetBindingByGuid("2bae6e96-3fab-4270-8a62-7e30522de4ba", "scale", out InternalGenericScale_GenericScale_value_Binding))
			{
				_transformViaCoherenceSync_2515451422962040544 = (Coherence.Toolkit.CoherenceSync)InternalGenericScale_GenericScale_value_Binding.Component.GetComponent<CoherenceSync>();
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).scale");
			}

			if (coherenceSync.TryGetBindingByGuid("8714eb6b-cd94-411f-8955-92513641b9de", "velocity", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).velocity");
			}

			if (coherenceSync.TryGetBindingByGuid("3dc4575b-7dc3-4c9f-9bbe-c7001762f6c5", "angularVelocity", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).angularVelocity");
			}

			if (coherenceSync.TryGetBindingByGuid("d5516390-785e-4fe0-a59f-833a23eb5929", "drag", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).drag");
			}

			if (coherenceSync.TryGetBindingByGuid("a16c1f48-e0b8-4080-8cb7-a49867fed73f", "angularDrag", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).angularDrag");
			}

			if (coherenceSync.TryGetBindingByGuid("5ada097b-248a-4d35-b0a8-b8bf9a072889", "mass", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).mass");
			}

			if (coherenceSync.TryGetBindingByGuid("1dea67b2-76fe-480e-9dbe-0a7c1faf94e4", "useGravity", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).useGravity");
			}

			if (coherenceSync.TryGetBindingByGuid("a1ea3a35-5503-4d6e-a1bb-b15ebac47482", "maxDepenetrationVelocity", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).maxDepenetrationVelocity");
			}

			if (coherenceSync.TryGetBindingByGuid("10e59561-f2e2-4e52-89d1-6bdf404ad83a", "isKinematic", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).isKinematic");
			}

			if (coherenceSync.TryGetBindingByGuid("48580a5f-acb9-4f70-bc2f-89de7d0e6aae", "freezeRotation", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).freezeRotation");
			}

			if (coherenceSync.TryGetBindingByGuid("be4c0e38-4996-496c-a38d-d69b6b4e5c6d", "centerOfMass", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).centerOfMass");
			}

			if (coherenceSync.TryGetBindingByGuid("7f4d2133-d223-4fa0-b09c-ecbb336903ae", "inertiaTensorRotation", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).inertiaTensorRotation");
			}

			if (coherenceSync.TryGetBindingByGuid("fd6f913a-ea82-42f9-b821-876defe6f389", "inertiaTensor", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).inertiaTensor");
			}

			if (coherenceSync.TryGetBindingByGuid("d0f29aa5-d8a4-4c65-9543-836a50dc9a7f", "detectCollisions", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).detectCollisions");
			}

			if (coherenceSync.TryGetBindingByGuid("56458af1-f325-46eb-b4c8-2be484304aec", "position", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).position");
			}

			if (coherenceSync.TryGetBindingByGuid("086de099-4a9b-42a5-a5fb-03122e5a546d", "rotation", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).rotation");
			}

			if (coherenceSync.TryGetBindingByGuid("794f5838-4cf4-447f-96c9-b5e3b159afa7", "solverIterations", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverIterations");
			}

			if (coherenceSync.TryGetBindingByGuid("8213b910-e462-400f-84a8-4e151018e801", "sleepThreshold", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).sleepThreshold");
			}

			if (coherenceSync.TryGetBindingByGuid("bdd24369-e55c-4648-bdce-822714068ae2", "maxAngularVelocity", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).maxAngularVelocity");
			}

			if (coherenceSync.TryGetBindingByGuid("01ae9fe1-3bde-42f0-a38b-1c453f0bf404", "solverVelocityIterations", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverVelocityIterations");
			}

			if (coherenceSync.TryGetBindingByGuid("d77dcc75-d0c3-4d17-8a10-c7f9d037a249", "solverIterationCount", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverIterationCount");
			}

			if (coherenceSync.TryGetBindingByGuid("bac51177-c3f9-4f76-b94a-9a188f4d7b84", "solverVelocityIterationCount", out InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding))
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547 = (UnityEngine.Rigidbody)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.Component;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).solverVelocityIterationCount");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime)
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = Archetypes.IndexForName[coherenceSync.Archetype.ArchetypeName]
					}
				};

				return components;
			}

			return null;
		}

		private void OnDestroy()
		{
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}

			this.client = client;

			lastSerializedCoherenceUUID = coherenceSync.coherenceUUID;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncPuck_id2] Unhandled command: {command.GetType()}.");
					break;
			}
		}

		public override void SendUpdates()
		{
			SendComponentUpdates();
		}

		public override (List<ICoherenceComponentData>, List<uint>) GetLatestChanges()
		{
			var updates = new List<ICoherenceComponentData>();
			var masks = new List<uint>();

			if (coherenceSync.HasStateAuthority)
			{

				// Send Translation / WorldPosition
				{
					var update = _transformViaCoherenceSync_2515451422962040544_WorldPosition_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalWorldPosition_Translation_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_2515451422962040544.coherencePosition);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_2515451422962040544_WorldPosition_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_2515451422962040544_WorldPosition_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_2515451422962040544_WorldPosition_lastSentData = update;
					}
				}

				// Send Rotation / WorldOrientation
				{
					var update = _transformViaCoherenceSync_2515451422962040544_WorldOrientation_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalWorldOrientation_Rotation_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_2515451422962040544.coherenceRotation);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_2515451422962040544_WorldOrientation_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_2515451422962040544_WorldOrientation_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_2515451422962040544_WorldOrientation_lastSentData = update;
					}
				}

				// Send GenericScale / GenericScale
				{
					var update = _transformViaCoherenceSync_2515451422962040544_GenericScale_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalGenericScale_GenericScale_value_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.value = (_transformViaCoherenceSync_2515451422962040544.coherenceLocalScale);
					}

					uint mask = performedInitialSync ? _transformViaCoherenceSync_2515451422962040544_GenericScale_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_transformViaCoherenceSync_2515451422962040544_GenericScale_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_transformViaCoherenceSync_2515451422962040544_GenericScale_lastSentData = update;
					}
				}

				// Send Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547 / Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547
				{
					var update = _UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData;
				
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.velocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.velocity);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.angularVelocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.angularVelocity);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.drag = (_UnityEngine__char_46_Rigidbody_2515451422962040547.drag);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.angularDrag = (_UnityEngine__char_46_Rigidbody_2515451422962040547.angularDrag);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.mass = (_UnityEngine__char_46_Rigidbody_2515451422962040547.mass);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.useGravity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.useGravity);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.maxDepenetrationVelocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.maxDepenetrationVelocity);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.isKinematic = (_UnityEngine__char_46_Rigidbody_2515451422962040547.isKinematic);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.freezeRotation = (_UnityEngine__char_46_Rigidbody_2515451422962040547.freezeRotation);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.centerOfMass = (_UnityEngine__char_46_Rigidbody_2515451422962040547.centerOfMass);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.inertiaTensorRotation = (_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensorRotation);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.inertiaTensor = (_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensor);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.detectCollisions = (_UnityEngine__char_46_Rigidbody_2515451422962040547.detectCollisions);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.position = (_UnityEngine__char_46_Rigidbody_2515451422962040547.position);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.rotation = (_UnityEngine__char_46_Rigidbody_2515451422962040547.rotation);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverIterations = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.sleepThreshold = (_UnityEngine__char_46_Rigidbody_2515451422962040547.sleepThreshold);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.maxAngularVelocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.maxAngularVelocity);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverVelocityIterations = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverIterationCount = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations);
					}
					if (coherenceSync.IsReadyToSample(InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding, coherenceSync.MonoBridge.NetworkTime.TimeAsDouble))
					{
						update.solverVelocityIterationCount = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations);
					}

					uint mask = performedInitialSync ? _UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.DiffWith(update) : 0b11111111111111111111111111111111;

					update.ResetByteArrays(_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData, mask);

					if(mask != 0)
					{
						updates.Add(update);
						masks.Add(mask);
						_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData = update;
					}
				}

				if (coherenceSync.coherenceUUID != lastSerializedCoherenceUUID)
				{
					var update = Impl.GetRootDefinition().GenerateCoherenceUUIDData(coherenceSync.coherenceUUID);
					var mask = 0b11111111111111111111111111111111;

					updates.Add(update);
					masks.Add(mask);

					lastSerializedCoherenceUUID = coherenceSync.coherenceUUID;
				}
				performedInitialSync = true;
			}

			return (updates, masks);
		}

		public override void PerformInterpolation()
		{
			if (InternalWorldPosition_Translation_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_2515451422962040544.coherencePosition = (UnityEngine.Vector3)InternalWorldPosition_Translation_value_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_transformViaCoherenceSync_2515451422962040544.coherencePosition, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalWorldOrientation_Rotation_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_2515451422962040544.coherenceRotation = (UnityEngine.Quaternion)InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_transformViaCoherenceSync_2515451422962040544.coherenceRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalGenericScale_GenericScale_value_Binding.ShouldApplyNetworkData())
			{
				_transformViaCoherenceSync_2515451422962040544.coherenceLocalScale = (UnityEngine.Vector3)InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_transformViaCoherenceSync_2515451422962040544.coherenceLocalScale, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.velocity = (UnityEngine.Vector3)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_2515451422962040547.velocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.angularVelocity = (UnityEngine.Vector3)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_2515451422962040547.angularVelocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.drag = (System.Single)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_2515451422962040547.drag, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.angularDrag = (System.Single)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_2515451422962040547.angularDrag, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.mass = (System.Single)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_2515451422962040547.mass, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.useGravity = (System.Boolean)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_2515451422962040547.useGravity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.maxDepenetrationVelocity = (System.Single)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_2515451422962040547.maxDepenetrationVelocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.isKinematic = (System.Boolean)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_2515451422962040547.isKinematic, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.freezeRotation = (System.Boolean)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_2515451422962040547.freezeRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.centerOfMass = (UnityEngine.Vector3)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_2515451422962040547.centerOfMass, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensorRotation = (UnityEngine.Quaternion)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensorRotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensor = (UnityEngine.Vector3)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensor, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.detectCollisions = (System.Boolean)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.InterpolationSettings.PerformInterpolationBoolean((bool)_UnityEngine__char_46_Rigidbody_2515451422962040547.detectCollisions, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.position = (UnityEngine.Vector3)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.InterpolationSettings.PerformInterpolationVector3((Vector3)_UnityEngine__char_46_Rigidbody_2515451422962040547.position, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.rotation = (UnityEngine.Quaternion)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.InterpolationSettings.PerformInterpolationQuaternion((Quaternion)_UnityEngine__char_46_Rigidbody_2515451422962040547.rotation, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations = (System.Int32)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.sleepThreshold = (System.Single)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_2515451422962040547.sleepThreshold, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.maxAngularVelocity = (System.Single)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.InterpolationSettings.PerformInterpolationFloat((float)_UnityEngine__char_46_Rigidbody_2515451422962040547.maxAngularVelocity, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations = (System.Int32)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations = (System.Int32)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
			if (InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.ShouldApplyNetworkData())
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations = (System.Int32)InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.InterpolationSettings.PerformInterpolationInt((int)_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations, monoBridge.NetworkTime.TimeAsDouble) ;
			}
		}

		public override void ResetInterpolation(bool setToLastSamples)
		{
			if (setToLastSamples && InternalWorldPosition_Translation_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalWorldPosition_Translation_value_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_transformViaCoherenceSync_2515451422962040544.coherencePosition = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalWorldPosition_Translation_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_transformViaCoherenceSync_2515451422962040544.coherenceRotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalWorldOrientation_Rotation_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_transformViaCoherenceSync_2515451422962040544.coherenceLocalScale = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalGenericScale_GenericScale_value_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.velocity = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.angularVelocity = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.drag = (System.Single)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.angularDrag = (System.Single)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.mass = (System.Single)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.useGravity = (System.Boolean)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.maxDepenetrationVelocity = (System.Single)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.isKinematic = (System.Boolean)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.freezeRotation = (System.Boolean)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.centerOfMass = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensorRotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensor = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.InterpolationSettings.GetLastSample<bool>();
				if (sample != null) 
				{
					bool lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.detectCollisions = (System.Boolean)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.InterpolationSettings.GetLastSample<Vector3>();
				if (sample != null) 
				{
					Vector3 lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.position = (UnityEngine.Vector3)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.InterpolationSettings.GetLastSample<Quaternion>();
				if (sample != null) 
				{
					Quaternion lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.rotation = (UnityEngine.Quaternion)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations = (System.Int32)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.sleepThreshold = (System.Single)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.InterpolationSettings.GetLastSample<float>();
				if (sample != null) 
				{
					float lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.maxAngularVelocity = (System.Single)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations = (System.Int32)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations = (System.Int32)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.InterpolationSettings.Reset();
			if (setToLastSamples && InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.InterpolationSettings.GetSampleType() != null)
			{
				var sample = InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.InterpolationSettings.GetLastSample<int>();
				if (sample != null) 
				{
					int lastSample = sample.Value;
					_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations = (System.Int32)lastSample;
				}
			}
			InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.InterpolationSettings.Reset();
		}		

		public override void ResetLastSentData()
		{
			// Translation / WorldPosition
			{
				_transformViaCoherenceSync_2515451422962040544_WorldPosition_lastSentData.value = (_transformViaCoherenceSync_2515451422962040544.coherencePosition);
			}
			// Rotation / WorldOrientation
			{
				_transformViaCoherenceSync_2515451422962040544_WorldOrientation_lastSentData.value = (_transformViaCoherenceSync_2515451422962040544.coherenceRotation);
			}
			// GenericScale / GenericScale
			{
				_transformViaCoherenceSync_2515451422962040544_GenericScale_lastSentData.value = (_transformViaCoherenceSync_2515451422962040544.coherenceLocalScale);
			}
			// Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547 / Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547
			{
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.velocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.velocity);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.angularVelocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.angularVelocity);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.drag = (_UnityEngine__char_46_Rigidbody_2515451422962040547.drag);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.angularDrag = (_UnityEngine__char_46_Rigidbody_2515451422962040547.angularDrag);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.mass = (_UnityEngine__char_46_Rigidbody_2515451422962040547.mass);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.useGravity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.useGravity);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.maxDepenetrationVelocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.maxDepenetrationVelocity);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.isKinematic = (_UnityEngine__char_46_Rigidbody_2515451422962040547.isKinematic);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.freezeRotation = (_UnityEngine__char_46_Rigidbody_2515451422962040547.freezeRotation);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.centerOfMass = (_UnityEngine__char_46_Rigidbody_2515451422962040547.centerOfMass);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.inertiaTensorRotation = (_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensorRotation);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.inertiaTensor = (_UnityEngine__char_46_Rigidbody_2515451422962040547.inertiaTensor);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.detectCollisions = (_UnityEngine__char_46_Rigidbody_2515451422962040547.detectCollisions);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.position = (_UnityEngine__char_46_Rigidbody_2515451422962040547.position);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.rotation = (_UnityEngine__char_46_Rigidbody_2515451422962040547.rotation);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.solverIterations = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.sleepThreshold = (_UnityEngine__char_46_Rigidbody_2515451422962040547.sleepThreshold);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.maxAngularVelocity = (_UnityEngine__char_46_Rigidbody_2515451422962040547.maxAngularVelocity);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.solverVelocityIterations = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.solverIterationCount = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverIterations);
				_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_lastSentData.solverVelocityIterationCount = (_UnityEngine__char_46_Rigidbody_2515451422962040547.solverVelocityIterations);
			}
		}

		private void SendComponentUpdates()
		{
			var entity = coherenceSync.EntityID;

			if (coherenceSync.HasStateAuthority)
			{
				var (updates, masks) = GetLatestChanges();

				if (updates.Count > 0)
				{
					client.UpdateComponents(coherenceSync.EntityID, updates.ToArray(), masks.ToArray());
				}
			}
		}

		public override void ApplyComponentUpdates(EntityData entityData)
		{
			// Sort component changes by (order, index) using Linq to ensure consistent replication order, regardless of ordering in packet.
			// Multiplying by a constant value is faster than using Linq .ThenBy extension method.
			updateBuff.Clear();
			updateBuff.AddRange(entityData.Store.Values);
			updateBuff.Sort((a, b) => (a.Data.GetComponentOrder() * 10000 + a.Data.GetComponentType()).CompareTo(
				b.Data.GetComponentOrder() * 10000 + b.Data.GetComponentType()));

			foreach (var change in updateBuff)
			{
				var componentType = change.Data.GetComponentType();

				switch(componentType)
				{

					case 0:
					{
						// Translation
						var data = (WorldPosition)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalWorldPosition_Translation_value_Binding.ReceiveSampleFromNetwork<Vector3>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 1:
					{
						// Rotation
						var data = (WorldOrientation)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalWorldOrientation_Rotation_value_Binding.ReceiveSampleFromNetwork<Quaternion>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 15:
					{
						// GenericScale
						var data = (GenericScale)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalGenericScale_GenericScale_value_Binding.ReceiveSampleFromNetwork<Vector3>(data.value, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case 111:
					{
						// Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547
						var data = (Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547)change.Data;
						var mask = change.Mask;
						if((mask & 0b00000000000000000000000000000001) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_velocity_Binding.ReceiveSampleFromNetwork<Vector3>(data.velocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000000010) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularVelocity_Binding.ReceiveSampleFromNetwork<Vector3>(data.angularVelocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000000100) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_drag_Binding.ReceiveSampleFromNetwork<float>(data.drag, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000001000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_angularDrag_Binding.ReceiveSampleFromNetwork<float>(data.angularDrag, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000010000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_mass_Binding.ReceiveSampleFromNetwork<float>(data.mass, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000000100000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_useGravity_Binding.ReceiveSampleFromNetwork<bool>(data.useGravity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000001000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxDepenetrationVelocity_Binding.ReceiveSampleFromNetwork<float>(data.maxDepenetrationVelocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000010000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_isKinematic_Binding.ReceiveSampleFromNetwork<bool>(data.isKinematic, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000000100000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_freezeRotation_Binding.ReceiveSampleFromNetwork<bool>(data.freezeRotation, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000001000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_centerOfMass_Binding.ReceiveSampleFromNetwork<Vector3>(data.centerOfMass, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000010000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensorRotation_Binding.ReceiveSampleFromNetwork<Quaternion>(data.inertiaTensorRotation, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000000100000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_inertiaTensor_Binding.ReceiveSampleFromNetwork<Vector3>(data.inertiaTensor, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000001000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_detectCollisions_Binding.ReceiveSampleFromNetwork<bool>(data.detectCollisions, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000010000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_position_Binding.ReceiveSampleFromNetwork<Vector3>(data.position, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000000100000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_rotation_Binding.ReceiveSampleFromNetwork<Quaternion>(data.rotation, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000001000000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterations_Binding.ReceiveSampleFromNetwork<int>(data.solverIterations, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000010000000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_sleepThreshold_Binding.ReceiveSampleFromNetwork<float>(data.sleepThreshold, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000000100000000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_maxAngularVelocity_Binding.ReceiveSampleFromNetwork<float>(data.maxAngularVelocity, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000001000000000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterations_Binding.ReceiveSampleFromNetwork<int>(data.solverVelocityIterations, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000010000000000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverIterationCount_Binding.ReceiveSampleFromNetwork<int>(data.solverIterationCount, data.GetSimulationFrame().Frame);
						}
						if((mask & 0b00000000000100000000000000000000) != 0)
						{
							InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_solverVelocityIterationCount_Binding.ReceiveSampleFromNetwork<int>(data.solverVelocityIterationCount, data.GetSimulationFrame().Frame);
						}
						break;
					}

					case Definition.InternalArchetypeComponent:
						// Handled internally by coherence Client Core
						break;
					case Definition.InternalGenericPrefabReference:
						// Handled internally by the coherence Mono Bridge
						break;
					case Definition.InternalUniqueID:
						coherenceSync.coherenceUUID = lastSerializedCoherenceUUID = Impl.GetRootDefinition().ExtractCoherenceUUID(change.Data);
						break;
					case Definition.InternalPersistence:
						break;
					case Definition.InternalConnectedEntity:
						var newConnectedEntity = Impl.GetRootDefinition().ExtractConnectedEntityID(change.Data);
						coherenceSync.ConnectedEntityChanged(newConnectedEntity);
						break;
					case Definition.InternalConnection:
					case Definition.InternalGlobal:
					case Definition.InternalGlobalQuery:
					case Definition.InternalTag:
					case Definition.InternalTagQuery:
					case Definition.InternalWorldPositionQuery:
						break;
					default:
						logger.Warning($"Unhandled component type ID: {componentType}");
						break;
					}
			}
		}

		private void AddDelayedEntityReference(SerializeEntityID id, ComponentChange componentChange)
		{
			if (delayedEntityReferences == null)
			{
				delayedEntityReferences = new Dictionary<SerializeEntityID, EntityData>();
			}

			EntityData entityData;

			if (!delayedEntityReferences.TryGetValue(id, out entityData))
			{
				entityData = EntityData.New();
			}

			entityData.Update(componentChange);
			delayedEntityReferences[id] = entityData;
		}

		private T FindCommandTarget<T>() where T : class
		{
			var targets = GetComponentsInChildren<T>();

			if (targets == null || targets.Length == 0)
			{
				logger.Error($"Couldn't find {nameof(T)} component in children.");
				
				return null;
			}

			if (targets.Length > 1)
			{
				logger.Error($"Found more than one {nameof(T)} component in children.");
			}

			return targets[0];
		}
	}
}
