// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Connection;
	using Coherence.Entity;
	using Coherence.Serializer;
	using Coherence.Log;
	using System.Collections.Generic;

	public class Definition : IDefinition
	{
		public const string schemaId = "69c67896ddef400526c6b0a7ca6d0c2b8530157f";
		public const uint InternalWorldPosition = 0;
		public const uint InternalWorldOrientation = 1;
		public const uint InternalLocalUser = 2;
		public const uint InternalWorldPositionQuery = 3;
		public const uint InternalArchetypeComponent = 4;
		public const uint InternalPersistence = 5;
		public const uint InternalConnectedEntity = 6;
		public const uint InternalUniqueID = 7;
		public const uint InternalConnection = 8;
		public const uint InternalGlobal = 9;
		public const uint InternalGlobalQuery = 10;
		public const uint InternalTag = 11;
		public const uint InternalTagQuery = 12;
		public const uint InternalGenericPrefabReference = 13;
		public const uint InternalGenericPrefabId = 14;
		public const uint InternalGenericScale = 15;
		public const uint InternalGenericFieldInt0 = 16;
		public const uint InternalGenericFieldInt1 = 17;
		public const uint InternalGenericFieldInt2 = 18;
		public const uint InternalGenericFieldInt3 = 19;
		public const uint InternalGenericFieldInt4 = 20;
		public const uint InternalGenericFieldInt5 = 21;
		public const uint InternalGenericFieldInt6 = 22;
		public const uint InternalGenericFieldInt7 = 23;
		public const uint InternalGenericFieldInt8 = 24;
		public const uint InternalGenericFieldInt9 = 25;
		public const uint InternalGenericFieldUInt0 = 26;
		public const uint InternalGenericFieldUInt1 = 27;
		public const uint InternalGenericFieldUInt2 = 28;
		public const uint InternalGenericFieldUInt3 = 29;
		public const uint InternalGenericFieldUInt4 = 30;
		public const uint InternalGenericFieldUInt5 = 31;
		public const uint InternalGenericFieldUInt6 = 32;
		public const uint InternalGenericFieldUInt7 = 33;
		public const uint InternalGenericFieldUInt8 = 34;
		public const uint InternalGenericFieldUInt9 = 35;
		public const uint InternalGenericFieldBool0 = 36;
		public const uint InternalGenericFieldBool1 = 37;
		public const uint InternalGenericFieldBool2 = 38;
		public const uint InternalGenericFieldBool3 = 39;
		public const uint InternalGenericFieldBool4 = 40;
		public const uint InternalGenericFieldBool5 = 41;
		public const uint InternalGenericFieldBool6 = 42;
		public const uint InternalGenericFieldBool7 = 43;
		public const uint InternalGenericFieldBool8 = 44;
		public const uint InternalGenericFieldBool9 = 45;
		public const uint InternalGenericFieldFloat0 = 46;
		public const uint InternalGenericFieldFloat1 = 47;
		public const uint InternalGenericFieldFloat2 = 48;
		public const uint InternalGenericFieldFloat3 = 49;
		public const uint InternalGenericFieldFloat4 = 50;
		public const uint InternalGenericFieldFloat5 = 51;
		public const uint InternalGenericFieldFloat6 = 52;
		public const uint InternalGenericFieldFloat7 = 53;
		public const uint InternalGenericFieldFloat8 = 54;
		public const uint InternalGenericFieldFloat9 = 55;
		public const uint InternalGenericFieldVector0 = 56;
		public const uint InternalGenericFieldVector1 = 57;
		public const uint InternalGenericFieldVector2 = 58;
		public const uint InternalGenericFieldVector3 = 59;
		public const uint InternalGenericField2dVector0 = 60;
		public const uint InternalGenericField2dVector1 = 61;
		public const uint InternalGenericField2dVector2 = 62;
		public const uint InternalGenericField2dVector3 = 63;
		public const uint InternalGenericFieldString0 = 64;
		public const uint InternalGenericFieldString1 = 65;
		public const uint InternalGenericFieldString2 = 66;
		public const uint InternalGenericFieldString3 = 67;
		public const uint InternalGenericFieldString4 = 68;
		public const uint InternalGenericFieldQuaternion0 = 69;
		public const uint InternalGenericFieldEntity0 = 70;
		public const uint InternalGenericFieldEntity1 = 71;
		public const uint InternalGenericFieldEntity2 = 72;
		public const uint InternalGenericFieldEntity3 = 73;
		public const uint InternalGenericFieldEntity4 = 74;
		public const uint InternalGenericFieldEntity5 = 75;
		public const uint InternalGenericFieldEntity6 = 76;
		public const uint InternalGenericFieldEntity7 = 77;
		public const uint InternalGenericFieldEntity8 = 78;
		public const uint InternalGenericFieldEntity9 = 79;
		public const uint InternalGenericFieldBytes0 = 80;
		public const uint InternalGenericFieldLong0 = 81;
		public const uint InternalGenericFieldLong1 = 82;
		public const uint InternalGenericFieldLong2 = 83;
		public const uint InternalGenericFieldLong3 = 84;
		public const uint InternalGenericFieldULong0 = 85;
		public const uint InternalGenericFieldULong1 = 86;
		public const uint InternalGenericFieldULong2 = 87;
		public const uint InternalGenericFieldULong3 = 88;
		public const uint InternalGenericFieldColor0 = 89;
		public const uint InternalGenericFieldColor1 = 90;
		public const uint InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390 = 91;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429 = 92;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403 = 93;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428 = 94;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102 = 95;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101 = 96;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363 = 97;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362 = 98;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959 = 99;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958 = 100;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008 = 101;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015 = 102;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982 = 103;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981 = 104;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627 = 105;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626 = 106;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056 = 107;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063 = 108;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151 = 109;
		public const uint InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150 = 110;
		public const uint InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547 = 111;
		public const uint InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034 = 112;
		public const uint InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldPosition_LOD0 = 113;
		public const uint InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldOrientation_LOD0 = 114;
		public const uint InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_GenericScale_LOD0 = 115;
		public const uint InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_LOD0 = 116;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldPosition_LOD0 = 117;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldOrientation_LOD0 = 118;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_GenericScale_LOD0 = 119;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429_LOD0 = 120;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403_LOD0 = 121;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428_LOD0 = 122;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102_LOD0 = 123;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101_LOD0 = 124;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363_LOD0 = 125;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362_LOD0 = 126;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959_LOD0 = 127;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958_LOD0 = 128;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008_LOD0 = 129;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015_LOD0 = 130;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982_LOD0 = 131;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981_LOD0 = 132;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627_LOD0 = 133;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626_LOD0 = 134;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056_LOD0 = 135;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063_LOD0 = 136;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151_LOD0 = 137;
		public const uint InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150_LOD0 = 138;
		public const uint InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldPosition_LOD0 = 139;
		public const uint InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldOrientation_LOD0 = 140;
		public const uint InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_GenericScale_LOD0 = 141;
		public const uint InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_LOD0 = 142;
		public const uint InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldPosition_LOD0 = 143;
		public const uint InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_GenericScale_LOD0 = 144;
		public const uint InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldOrientation_LOD0 = 145;
		public const uint InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_LOD0 = 146;
		public const uint InternalAuthorityRequest = 0;
		public const uint InternalAuthorityTransfer = 1;
		public const uint InternalQuerySynced = 2;
		public const uint InternalAdoptOrphan = 3;
		public const uint InternalPersistenceReady = 4;
		public const uint InternalGenericCommand = 5;

		private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>() {
			{ 0, "WorldPosition" },
			{ 1, "WorldOrientation" },
			{ 2, "LocalUser" },
			{ 3, "WorldPositionQuery" },
			{ 4, "ArchetypeComponent" },
			{ 5, "Persistence" },
			{ 6, "ConnectedEntity" },
			{ 7, "UniqueID" },
			{ 8, "Connection" },
			{ 9, "Global" },
			{ 10, "GlobalQuery" },
			{ 11, "Tag" },
			{ 12, "TagQuery" },
			{ 13, "GenericPrefabReference" },
			{ 14, "GenericPrefabId" },
			{ 15, "GenericScale" },
			{ 16, "GenericFieldInt0" },
			{ 17, "GenericFieldInt1" },
			{ 18, "GenericFieldInt2" },
			{ 19, "GenericFieldInt3" },
			{ 20, "GenericFieldInt4" },
			{ 21, "GenericFieldInt5" },
			{ 22, "GenericFieldInt6" },
			{ 23, "GenericFieldInt7" },
			{ 24, "GenericFieldInt8" },
			{ 25, "GenericFieldInt9" },
			{ 26, "GenericFieldUInt0" },
			{ 27, "GenericFieldUInt1" },
			{ 28, "GenericFieldUInt2" },
			{ 29, "GenericFieldUInt3" },
			{ 30, "GenericFieldUInt4" },
			{ 31, "GenericFieldUInt5" },
			{ 32, "GenericFieldUInt6" },
			{ 33, "GenericFieldUInt7" },
			{ 34, "GenericFieldUInt8" },
			{ 35, "GenericFieldUInt9" },
			{ 36, "GenericFieldBool0" },
			{ 37, "GenericFieldBool1" },
			{ 38, "GenericFieldBool2" },
			{ 39, "GenericFieldBool3" },
			{ 40, "GenericFieldBool4" },
			{ 41, "GenericFieldBool5" },
			{ 42, "GenericFieldBool6" },
			{ 43, "GenericFieldBool7" },
			{ 44, "GenericFieldBool8" },
			{ 45, "GenericFieldBool9" },
			{ 46, "GenericFieldFloat0" },
			{ 47, "GenericFieldFloat1" },
			{ 48, "GenericFieldFloat2" },
			{ 49, "GenericFieldFloat3" },
			{ 50, "GenericFieldFloat4" },
			{ 51, "GenericFieldFloat5" },
			{ 52, "GenericFieldFloat6" },
			{ 53, "GenericFieldFloat7" },
			{ 54, "GenericFieldFloat8" },
			{ 55, "GenericFieldFloat9" },
			{ 56, "GenericFieldVector0" },
			{ 57, "GenericFieldVector1" },
			{ 58, "GenericFieldVector2" },
			{ 59, "GenericFieldVector3" },
			{ 60, "GenericField2dVector0" },
			{ 61, "GenericField2dVector1" },
			{ 62, "GenericField2dVector2" },
			{ 63, "GenericField2dVector3" },
			{ 64, "GenericFieldString0" },
			{ 65, "GenericFieldString1" },
			{ 66, "GenericFieldString2" },
			{ 67, "GenericFieldString3" },
			{ 68, "GenericFieldString4" },
			{ 69, "GenericFieldQuaternion0" },
			{ 70, "GenericFieldEntity0" },
			{ 71, "GenericFieldEntity1" },
			{ 72, "GenericFieldEntity2" },
			{ 73, "GenericFieldEntity3" },
			{ 74, "GenericFieldEntity4" },
			{ 75, "GenericFieldEntity5" },
			{ 76, "GenericFieldEntity6" },
			{ 77, "GenericFieldEntity7" },
			{ 78, "GenericFieldEntity8" },
			{ 79, "GenericFieldEntity9" },
			{ 80, "GenericFieldBytes0" },
			{ 81, "GenericFieldLong0" },
			{ 82, "GenericFieldLong1" },
			{ 83, "GenericFieldLong2" },
			{ 84, "GenericFieldLong3" },
			{ 85, "GenericFieldULong0" },
			{ 86, "GenericFieldULong1" },
			{ 87, "GenericFieldULong2" },
			{ 88, "GenericFieldULong3" },
			{ 89, "GenericFieldColor0" },
			{ 90, "GenericFieldColor1" },
			{ 91, "FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390" },
			{ 92, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429" },
			{ 93, "AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403" },
			{ 94, "AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428" },
			{ 95, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102" },
			{ 96, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101" },
			{ 97, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363" },
			{ 98, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362" },
			{ 99, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959" },
			{ 100, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958" },
			{ 101, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008" },
			{ 102, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015" },
			{ 103, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982" },
			{ 104, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981" },
			{ 105, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627" },
			{ 106, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626" },
			{ 107, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056" },
			{ 108, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063" },
			{ 109, "AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151" },
			{ 110, "AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150" },
			{ 111, "Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547" },
			{ 112, "Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034" },
			{ 113, "ArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldPosition_LOD0" },
			{ 114, "ArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldOrientation_LOD0" },
			{ 115, "ArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_GenericScale_LOD0" },
			{ 116, "ArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_LOD0" },
			{ 117, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldPosition_LOD0" },
			{ 118, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldOrientation_LOD0" },
			{ 119, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_GenericScale_LOD0" },
			{ 120, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429_LOD0" },
			{ 121, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403_LOD0" },
			{ 122, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428_LOD0" },
			{ 123, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102_LOD0" },
			{ 124, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101_LOD0" },
			{ 125, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363_LOD0" },
			{ 126, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362_LOD0" },
			{ 127, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959_LOD0" },
			{ 128, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958_LOD0" },
			{ 129, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008_LOD0" },
			{ 130, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015_LOD0" },
			{ 131, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982_LOD0" },
			{ 132, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981_LOD0" },
			{ 133, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627_LOD0" },
			{ 134, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626_LOD0" },
			{ 135, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056_LOD0" },
			{ 136, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063_LOD0" },
			{ 137, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151_LOD0" },
			{ 138, "ArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150_LOD0" },
			{ 139, "ArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldPosition_LOD0" },
			{ 140, "ArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldOrientation_LOD0" },
			{ 141, "ArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_GenericScale_LOD0" },
			{ 142, "ArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_LOD0" },
			{ 143, "ArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldPosition_LOD0" },
			{ 144, "ArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_GenericScale_LOD0" },
			{ 145, "ArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldOrientation_LOD0" },
			{ 146, "ArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_LOD0" },
		};

		public static string ComponentNameForTypeId(uint typeId)
		{
			if(componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
			{
				return componentName;
			}
			else
			{
				return "";
			}
		}

		public (ICoherenceComponentData, uint, uint?) ReadComponentUpdate(uint componentType, 
			IInBitStream bitStream, Logger logger)
		{
			var inProtocolStream = new InProtocolBitStream(bitStream);

			switch (componentType)
			{
				case InternalWorldPosition:
					return WorldPosition.Deserialize(inProtocolStream);
				case InternalWorldOrientation:
					return WorldOrientation.Deserialize(inProtocolStream);
				case InternalLocalUser:
					return LocalUser.Deserialize(inProtocolStream);
				case InternalWorldPositionQuery:
					return WorldPositionQuery.Deserialize(inProtocolStream);
				case InternalArchetypeComponent:
					return ArchetypeComponent.Deserialize(inProtocolStream);
				case InternalPersistence:
					return Persistence.Deserialize(inProtocolStream);
				case InternalConnectedEntity:
					return ConnectedEntity.Deserialize(inProtocolStream);
				case InternalUniqueID:
					return UniqueID.Deserialize(inProtocolStream);
				case InternalConnection:
					return Connection.Deserialize(inProtocolStream);
				case InternalGlobal:
					return Global.Deserialize(inProtocolStream);
				case InternalGlobalQuery:
					return GlobalQuery.Deserialize(inProtocolStream);
				case InternalTag:
					return Tag.Deserialize(inProtocolStream);
				case InternalTagQuery:
					return TagQuery.Deserialize(inProtocolStream);
				case InternalGenericPrefabReference:
					return GenericPrefabReference.Deserialize(inProtocolStream);
				case InternalGenericPrefabId:
					return GenericPrefabId.Deserialize(inProtocolStream);
				case InternalGenericScale:
					return GenericScale.Deserialize(inProtocolStream);
				case InternalGenericFieldInt0:
					return GenericFieldInt0.Deserialize(inProtocolStream);
				case InternalGenericFieldInt1:
					return GenericFieldInt1.Deserialize(inProtocolStream);
				case InternalGenericFieldInt2:
					return GenericFieldInt2.Deserialize(inProtocolStream);
				case InternalGenericFieldInt3:
					return GenericFieldInt3.Deserialize(inProtocolStream);
				case InternalGenericFieldInt4:
					return GenericFieldInt4.Deserialize(inProtocolStream);
				case InternalGenericFieldInt5:
					return GenericFieldInt5.Deserialize(inProtocolStream);
				case InternalGenericFieldInt6:
					return GenericFieldInt6.Deserialize(inProtocolStream);
				case InternalGenericFieldInt7:
					return GenericFieldInt7.Deserialize(inProtocolStream);
				case InternalGenericFieldInt8:
					return GenericFieldInt8.Deserialize(inProtocolStream);
				case InternalGenericFieldInt9:
					return GenericFieldInt9.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt0:
					return GenericFieldUInt0.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt1:
					return GenericFieldUInt1.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt2:
					return GenericFieldUInt2.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt3:
					return GenericFieldUInt3.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt4:
					return GenericFieldUInt4.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt5:
					return GenericFieldUInt5.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt6:
					return GenericFieldUInt6.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt7:
					return GenericFieldUInt7.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt8:
					return GenericFieldUInt8.Deserialize(inProtocolStream);
				case InternalGenericFieldUInt9:
					return GenericFieldUInt9.Deserialize(inProtocolStream);
				case InternalGenericFieldBool0:
					return GenericFieldBool0.Deserialize(inProtocolStream);
				case InternalGenericFieldBool1:
					return GenericFieldBool1.Deserialize(inProtocolStream);
				case InternalGenericFieldBool2:
					return GenericFieldBool2.Deserialize(inProtocolStream);
				case InternalGenericFieldBool3:
					return GenericFieldBool3.Deserialize(inProtocolStream);
				case InternalGenericFieldBool4:
					return GenericFieldBool4.Deserialize(inProtocolStream);
				case InternalGenericFieldBool5:
					return GenericFieldBool5.Deserialize(inProtocolStream);
				case InternalGenericFieldBool6:
					return GenericFieldBool6.Deserialize(inProtocolStream);
				case InternalGenericFieldBool7:
					return GenericFieldBool7.Deserialize(inProtocolStream);
				case InternalGenericFieldBool8:
					return GenericFieldBool8.Deserialize(inProtocolStream);
				case InternalGenericFieldBool9:
					return GenericFieldBool9.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat0:
					return GenericFieldFloat0.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat1:
					return GenericFieldFloat1.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat2:
					return GenericFieldFloat2.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat3:
					return GenericFieldFloat3.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat4:
					return GenericFieldFloat4.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat5:
					return GenericFieldFloat5.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat6:
					return GenericFieldFloat6.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat7:
					return GenericFieldFloat7.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat8:
					return GenericFieldFloat8.Deserialize(inProtocolStream);
				case InternalGenericFieldFloat9:
					return GenericFieldFloat9.Deserialize(inProtocolStream);
				case InternalGenericFieldVector0:
					return GenericFieldVector0.Deserialize(inProtocolStream);
				case InternalGenericFieldVector1:
					return GenericFieldVector1.Deserialize(inProtocolStream);
				case InternalGenericFieldVector2:
					return GenericFieldVector2.Deserialize(inProtocolStream);
				case InternalGenericFieldVector3:
					return GenericFieldVector3.Deserialize(inProtocolStream);
				case InternalGenericField2dVector0:
					return GenericField2dVector0.Deserialize(inProtocolStream);
				case InternalGenericField2dVector1:
					return GenericField2dVector1.Deserialize(inProtocolStream);
				case InternalGenericField2dVector2:
					return GenericField2dVector2.Deserialize(inProtocolStream);
				case InternalGenericField2dVector3:
					return GenericField2dVector3.Deserialize(inProtocolStream);
				case InternalGenericFieldString0:
					return GenericFieldString0.Deserialize(inProtocolStream);
				case InternalGenericFieldString1:
					return GenericFieldString1.Deserialize(inProtocolStream);
				case InternalGenericFieldString2:
					return GenericFieldString2.Deserialize(inProtocolStream);
				case InternalGenericFieldString3:
					return GenericFieldString3.Deserialize(inProtocolStream);
				case InternalGenericFieldString4:
					return GenericFieldString4.Deserialize(inProtocolStream);
				case InternalGenericFieldQuaternion0:
					return GenericFieldQuaternion0.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity0:
					return GenericFieldEntity0.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity1:
					return GenericFieldEntity1.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity2:
					return GenericFieldEntity2.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity3:
					return GenericFieldEntity3.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity4:
					return GenericFieldEntity4.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity5:
					return GenericFieldEntity5.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity6:
					return GenericFieldEntity6.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity7:
					return GenericFieldEntity7.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity8:
					return GenericFieldEntity8.Deserialize(inProtocolStream);
				case InternalGenericFieldEntity9:
					return GenericFieldEntity9.Deserialize(inProtocolStream);
				case InternalGenericFieldBytes0:
					return GenericFieldBytes0.Deserialize(inProtocolStream);
				case InternalGenericFieldLong0:
					return GenericFieldLong0.Deserialize(inProtocolStream);
				case InternalGenericFieldLong1:
					return GenericFieldLong1.Deserialize(inProtocolStream);
				case InternalGenericFieldLong2:
					return GenericFieldLong2.Deserialize(inProtocolStream);
				case InternalGenericFieldLong3:
					return GenericFieldLong3.Deserialize(inProtocolStream);
				case InternalGenericFieldULong0:
					return GenericFieldULong0.Deserialize(inProtocolStream);
				case InternalGenericFieldULong1:
					return GenericFieldULong1.Deserialize(inProtocolStream);
				case InternalGenericFieldULong2:
					return GenericFieldULong2.Deserialize(inProtocolStream);
				case InternalGenericFieldULong3:
					return GenericFieldULong3.Deserialize(inProtocolStream);
				case InternalGenericFieldColor0:
					return GenericFieldColor0.Deserialize(inProtocolStream);
				case InternalGenericFieldColor1:
					return GenericFieldColor1.Deserialize(inProtocolStream);
				case InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390:
					return FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403:
					return AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428:
					return AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151.Deserialize(inProtocolStream);
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150.Deserialize(inProtocolStream);
				case InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547:
					return Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547.Deserialize(inProtocolStream);
				case InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034:
					return Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034.Deserialize(inProtocolStream);
				case InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_LOD0:
					return FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390.DeserializeArchetypeFloorPlane_8eb27a8d75b38914780fb01a3d8b2d6a_FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151_LOD0(inProtocolStream);
				case InternalArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150_LOD0:
					return AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150.DeserializeArchetypeAirHockeyTable_1b8979aab75cc3548ac0742146ec7eed_AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150_LOD0(inProtocolStream);
				case InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_LOD0:
					return Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547.DeserializeArchetypePuck_67d153e8cb5779a49a2e569ee35a4437_Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547_LOD0(inProtocolStream);
				case InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldPosition_LOD0:
					return WorldPosition.DeserializeArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldPosition_LOD0(inProtocolStream);
				case InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_GenericScale_LOD0:
					return GenericScale.DeserializeArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_GenericScale_LOD0(inProtocolStream);
				case InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldOrientation_LOD0:
					return WorldOrientation.DeserializeArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_WorldOrientation_LOD0(inProtocolStream);
				case InternalArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_LOD0:
					return Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034.DeserializeArchetypeMallet_38e627b1eb339e74eb512bd8e1020e39_Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034_LOD0(inProtocolStream);
				default:
					return (null, 0, 0);
			}
		}

		public void WriteComponentUpdate(ICoherenceComponentData data, uint mask, 
			IOutProtocolBitStream protocolStream, Logger logger)
		{
			switch (data.GetComponentType())
			{
				case InternalWorldPosition:
					WorldPosition.Serialize((WorldPosition)data, mask, protocolStream);
					break;
				case InternalWorldOrientation:
					WorldOrientation.Serialize((WorldOrientation)data, mask, protocolStream);
					break;
				case InternalLocalUser:
					LocalUser.Serialize((LocalUser)data, mask, protocolStream);
					break;
				case InternalWorldPositionQuery:
					WorldPositionQuery.Serialize((WorldPositionQuery)data, mask, protocolStream);
					break;
				case InternalArchetypeComponent:
					ArchetypeComponent.Serialize((ArchetypeComponent)data, mask, protocolStream);
					break;
				case InternalPersistence:
					Persistence.Serialize((Persistence)data, mask, protocolStream);
					break;
				case InternalConnectedEntity:
					ConnectedEntity.Serialize((ConnectedEntity)data, mask, protocolStream);
					break;
				case InternalUniqueID:
					UniqueID.Serialize((UniqueID)data, mask, protocolStream);
					break;
				case InternalConnection:
					Connection.Serialize((Connection)data, mask, protocolStream);
					break;
				case InternalGlobal:
					Global.Serialize((Global)data, mask, protocolStream);
					break;
				case InternalGlobalQuery:
					GlobalQuery.Serialize((GlobalQuery)data, mask, protocolStream);
					break;
				case InternalTag:
					Tag.Serialize((Tag)data, mask, protocolStream);
					break;
				case InternalTagQuery:
					TagQuery.Serialize((TagQuery)data, mask, protocolStream);
					break;
				case InternalGenericPrefabReference:
					GenericPrefabReference.Serialize((GenericPrefabReference)data, mask, protocolStream);
					break;
				case InternalGenericPrefabId:
					GenericPrefabId.Serialize((GenericPrefabId)data, mask, protocolStream);
					break;
				case InternalGenericScale:
					GenericScale.Serialize((GenericScale)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt0:
					GenericFieldInt0.Serialize((GenericFieldInt0)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt1:
					GenericFieldInt1.Serialize((GenericFieldInt1)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt2:
					GenericFieldInt2.Serialize((GenericFieldInt2)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt3:
					GenericFieldInt3.Serialize((GenericFieldInt3)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt4:
					GenericFieldInt4.Serialize((GenericFieldInt4)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt5:
					GenericFieldInt5.Serialize((GenericFieldInt5)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt6:
					GenericFieldInt6.Serialize((GenericFieldInt6)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt7:
					GenericFieldInt7.Serialize((GenericFieldInt7)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt8:
					GenericFieldInt8.Serialize((GenericFieldInt8)data, mask, protocolStream);
					break;
				case InternalGenericFieldInt9:
					GenericFieldInt9.Serialize((GenericFieldInt9)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt0:
					GenericFieldUInt0.Serialize((GenericFieldUInt0)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt1:
					GenericFieldUInt1.Serialize((GenericFieldUInt1)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt2:
					GenericFieldUInt2.Serialize((GenericFieldUInt2)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt3:
					GenericFieldUInt3.Serialize((GenericFieldUInt3)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt4:
					GenericFieldUInt4.Serialize((GenericFieldUInt4)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt5:
					GenericFieldUInt5.Serialize((GenericFieldUInt5)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt6:
					GenericFieldUInt6.Serialize((GenericFieldUInt6)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt7:
					GenericFieldUInt7.Serialize((GenericFieldUInt7)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt8:
					GenericFieldUInt8.Serialize((GenericFieldUInt8)data, mask, protocolStream);
					break;
				case InternalGenericFieldUInt9:
					GenericFieldUInt9.Serialize((GenericFieldUInt9)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool0:
					GenericFieldBool0.Serialize((GenericFieldBool0)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool1:
					GenericFieldBool1.Serialize((GenericFieldBool1)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool2:
					GenericFieldBool2.Serialize((GenericFieldBool2)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool3:
					GenericFieldBool3.Serialize((GenericFieldBool3)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool4:
					GenericFieldBool4.Serialize((GenericFieldBool4)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool5:
					GenericFieldBool5.Serialize((GenericFieldBool5)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool6:
					GenericFieldBool6.Serialize((GenericFieldBool6)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool7:
					GenericFieldBool7.Serialize((GenericFieldBool7)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool8:
					GenericFieldBool8.Serialize((GenericFieldBool8)data, mask, protocolStream);
					break;
				case InternalGenericFieldBool9:
					GenericFieldBool9.Serialize((GenericFieldBool9)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat0:
					GenericFieldFloat0.Serialize((GenericFieldFloat0)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat1:
					GenericFieldFloat1.Serialize((GenericFieldFloat1)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat2:
					GenericFieldFloat2.Serialize((GenericFieldFloat2)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat3:
					GenericFieldFloat3.Serialize((GenericFieldFloat3)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat4:
					GenericFieldFloat4.Serialize((GenericFieldFloat4)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat5:
					GenericFieldFloat5.Serialize((GenericFieldFloat5)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat6:
					GenericFieldFloat6.Serialize((GenericFieldFloat6)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat7:
					GenericFieldFloat7.Serialize((GenericFieldFloat7)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat8:
					GenericFieldFloat8.Serialize((GenericFieldFloat8)data, mask, protocolStream);
					break;
				case InternalGenericFieldFloat9:
					GenericFieldFloat9.Serialize((GenericFieldFloat9)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector0:
					GenericFieldVector0.Serialize((GenericFieldVector0)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector1:
					GenericFieldVector1.Serialize((GenericFieldVector1)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector2:
					GenericFieldVector2.Serialize((GenericFieldVector2)data, mask, protocolStream);
					break;
				case InternalGenericFieldVector3:
					GenericFieldVector3.Serialize((GenericFieldVector3)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector0:
					GenericField2dVector0.Serialize((GenericField2dVector0)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector1:
					GenericField2dVector1.Serialize((GenericField2dVector1)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector2:
					GenericField2dVector2.Serialize((GenericField2dVector2)data, mask, protocolStream);
					break;
				case InternalGenericField2dVector3:
					GenericField2dVector3.Serialize((GenericField2dVector3)data, mask, protocolStream);
					break;
				case InternalGenericFieldString0:
					GenericFieldString0.Serialize((GenericFieldString0)data, mask, protocolStream);
					break;
				case InternalGenericFieldString1:
					GenericFieldString1.Serialize((GenericFieldString1)data, mask, protocolStream);
					break;
				case InternalGenericFieldString2:
					GenericFieldString2.Serialize((GenericFieldString2)data, mask, protocolStream);
					break;
				case InternalGenericFieldString3:
					GenericFieldString3.Serialize((GenericFieldString3)data, mask, protocolStream);
					break;
				case InternalGenericFieldString4:
					GenericFieldString4.Serialize((GenericFieldString4)data, mask, protocolStream);
					break;
				case InternalGenericFieldQuaternion0:
					GenericFieldQuaternion0.Serialize((GenericFieldQuaternion0)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity0:
					GenericFieldEntity0.Serialize((GenericFieldEntity0)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity1:
					GenericFieldEntity1.Serialize((GenericFieldEntity1)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity2:
					GenericFieldEntity2.Serialize((GenericFieldEntity2)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity3:
					GenericFieldEntity3.Serialize((GenericFieldEntity3)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity4:
					GenericFieldEntity4.Serialize((GenericFieldEntity4)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity5:
					GenericFieldEntity5.Serialize((GenericFieldEntity5)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity6:
					GenericFieldEntity6.Serialize((GenericFieldEntity6)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity7:
					GenericFieldEntity7.Serialize((GenericFieldEntity7)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity8:
					GenericFieldEntity8.Serialize((GenericFieldEntity8)data, mask, protocolStream);
					break;
				case InternalGenericFieldEntity9:
					GenericFieldEntity9.Serialize((GenericFieldEntity9)data, mask, protocolStream);
					break;
				case InternalGenericFieldBytes0:
					GenericFieldBytes0.Serialize((GenericFieldBytes0)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong0:
					GenericFieldLong0.Serialize((GenericFieldLong0)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong1:
					GenericFieldLong1.Serialize((GenericFieldLong1)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong2:
					GenericFieldLong2.Serialize((GenericFieldLong2)data, mask, protocolStream);
					break;
				case InternalGenericFieldLong3:
					GenericFieldLong3.Serialize((GenericFieldLong3)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong0:
					GenericFieldULong0.Serialize((GenericFieldULong0)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong1:
					GenericFieldULong1.Serialize((GenericFieldULong1)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong2:
					GenericFieldULong2.Serialize((GenericFieldULong2)data, mask, protocolStream);
					break;
				case InternalGenericFieldULong3:
					GenericFieldULong3.Serialize((GenericFieldULong3)data, mask, protocolStream);
					break;
				case InternalGenericFieldColor0:
					GenericFieldColor0.Serialize((GenericFieldColor0)data, mask, protocolStream);
					break;
				case InternalGenericFieldColor1:
					GenericFieldColor1.Serialize((GenericFieldColor1)data, mask, protocolStream);
					break;
				case InternalFloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390:
					FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390.Serialize((FloorPlane_id0_UnityEngine__char_46_MeshCollider_124998048203007390)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279819150429)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403:
					AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403.Serialize((AirHockeyTable_id1_UnityEngine__char_46_MeshCollider_8131950279819150403)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428:
					AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Rigidbody_8131950279819150428)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280129045102)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280129045101)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279977235363)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279977235362)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279713318959)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279713318958)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279341121008)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279341121015)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279048504982)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279048504981)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279584126627)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279584126626)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950280497774056)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950280497774063)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151:
					AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151.Serialize((AirHockeyTable_id1_UnityEngine__char_46_Transform_8131950279831179151)data, mask, protocolStream);
					break;
				case InternalAirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150:
					AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150.Serialize((AirHockeyTable_id1_UnityEngine__char_46_BoxCollider_8131950279831179150)data, mask, protocolStream);
					break;
				case InternalPuck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547:
					Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547.Serialize((Puck_id2_UnityEngine__char_46_Rigidbody_2515451422962040547)data, mask, protocolStream);
					break;
				case InternalMallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034:
					Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034.Serialize((Mallet_id3_UnityEngine__char_46_Rigidbody_3239353100064038034)data, mask, protocolStream);
					break;
			}
		}

		private IEntityCommand ReadCommand(uint commandType, IInProtocolBitStream bitStream, Logger logger)
		{
			switch (commandType)
			{
				case Definition.InternalAuthorityRequest:
					return AuthorityRequest.Deserialize(bitStream);
				case Definition.InternalAuthorityTransfer:
					return AuthorityTransfer.Deserialize(bitStream);
				case Definition.InternalQuerySynced:
					return QuerySynced.Deserialize(bitStream);
				case Definition.InternalAdoptOrphan:
					return AdoptOrphan.Deserialize(bitStream);
				case Definition.InternalPersistenceReady:
					return PersistenceReady.Deserialize(bitStream);
				case Definition.InternalGenericCommand:
					return GenericCommand.Deserialize(bitStream);
				default:
					break;
			}

			return default;
		}

		private IEntityInput ReadInput(uint inputType, IInProtocolBitStream bitStream, Logger logger)
		{
			switch (inputType)
			{
				default:
					break;
			}

			return default;
		}

		public (IEntityCommand command, SerializeEntityID entityId, MessageTarget messageTarget)[]
			ReadCommands(IInBitStream bitStream, Logger logger)
		{
			var numMessages = bitStream.ReadUint8();

			var commandData = new (IEntityCommand command, SerializeEntityID entityId, MessageTarget messageTarget)[numMessages];

			for (var i = 0; i < numMessages; i++)
			{
				commandData[i].entityId = DeserializerTools.DeserializeEntityID(bitStream);
				commandData[i].messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
				var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
				var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
				commandData[i].command = ReadCommand(componentType, inBitStream, logger);
			}

			return commandData;
		}

		public (IEntityInput input, long frame, SerializeEntityID entityId)[] 
			ReadInputs(IInBitStream bitStream, Logger logger)
		{
			var numMessages = bitStream.ReadUint8();

			var inputData = new (IEntityInput input, long frame, SerializeEntityID entityId)[numMessages];

			for (var i = 0; i < numMessages; i++)
			{
				inputData[i].entityId = DeserializerTools.DeserializeEntityID(bitStream);
				_ = DeserializerTools.DeserializeMessageTarget(bitStream);
				var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
				var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
				inputData[i].frame = (long)bitStream.ReadUint64();
				inputData[i].input = ReadInput(componentType, inBitStream, logger);
			}

			return inputData;
		}

		public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
		{
			switch (commandType)
			{
				case Definition.InternalAuthorityRequest:
					AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
					break;
				case Definition.InternalAuthorityTransfer:
					AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
					break;
				case Definition.InternalQuerySynced:
					QuerySynced.Serialize((QuerySynced)data, bitStream);
					break;
				case Definition.InternalAdoptOrphan:
					AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
					break;
				case Definition.InternalPersistenceReady:
					PersistenceReady.Serialize((PersistenceReady)data, bitStream);
					break;
				case Definition.InternalGenericCommand:
					GenericCommand.Serialize((GenericCommand)data, bitStream);
					break;
				default:
					break;
			}
		}

		public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
		{
			var inputData = (InputData)data;
			bitStream.WriteLong(inputData.Frame);

			switch (inputType)
			{
				default:
					break;
			}
		}

		public IEntityCommand CreateAuthorityRequest(ClientID requester, AuthorityType authType)
		{
			return new AuthorityRequest((uint)requester, (int)authType);
		}

		public IEntityCommand CreateAdoptOrphanCommand()
		{
			return new AdoptOrphan();
		}

		public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand, 
			out ClientID requester, out AuthorityType authType)
		{
			if (entityCommand is AuthorityRequest request) 
			{
				requester = (ClientID)request.requester;
				authType = (AuthorityType)request.authorityType;

				return true;
			}

			requester = default;
			authType = default;

			return false;
		}

		public IEntityCommand CreateAuthorityTransfer(ClientID newAuthority, bool accepted, AuthorityType authType)
		{
			return new AuthorityTransfer((uint)newAuthority, accepted, (int)authType);
		}

		public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
			out bool transferAccepted, out AuthorityType authType) 
		{
			if (entityCommand is AuthorityTransfer transfer) 
			{
				newAuthority = (ClientID)transfer.newAuthority;
				transferAccepted = transfer.accepted;
				authType = (AuthorityType)transfer.authorityType;

				return true;
			}

			newAuthority = default;
			transferAccepted = default;
			authType = default;

			return false;
		}

		public ICoherenceComponentData GeneratePersistenceData()
		{
			var persistence = new Persistence();

			return persistence;
		}

		public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid)
		{
			var uniqueID = new UniqueID();
			uniqueID.uuid = uuid;

			return uniqueID;
		}

		public ICoherenceComponentData GenerateGlobalQueryComponent()
		{
			return new GlobalQuery();
		}

		public string ExtractCoherenceUUID(ICoherenceComponentData data)
		{
			var uniqueID = (UniqueID)data;
			return uniqueID.uuid;
		}

		public bool IsConnectedEntity(ICoherenceComponentData data)
		{
			return data.GetComponentType() == Definition.InternalConnectedEntity;
		}

		public SerializeEntityID ExtractConnectedEntityID(ICoherenceComponentData data)
		{
			var connectedEntity = (ConnectedEntity)data;

			return connectedEntity.value;
		}

		public string ExtractCoherenceTag(ICoherenceComponentData data)
		{
			var tag = (Tag)data;
			return tag.tag;
		}
	}
}